### ISSUE TITLE
Add null safety support

### ISSUE THREAD

**Issue by iabhishek3** [wogaa/wogaa_flutter_tracker#2]
**Description:**
Hi, I am currently using the `wogaa_flutter_tracker` package in my Flutter project. However, I am encountering an issue because the package does not support null safety. 

**Issue:**
When trying to resolve dependencies, I get the following error:
```
Because svc_lite depends on wogaa_flutter_tracker from git which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.7.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
exit code 1
```

**Steps to Reproduce:**
1. Add `wogaa_flutter_tracker` to the `pubspec.yaml` dependencies:
    ```yaml
    dependencies:
      wogaa_flutter_tracker:
        git:
          url: https://github.com/wogaa/wogaa_flutter_tracker.git
          ref: v2.0.0
    ```
2. Run `flutter pub get`.

**Expected Behavior:**
The package should support null safety and not cause a version solving failure.

**Environment:**
- Flutter version: Flutter (Channel stable, 3.13.3, on macOS 14.5 23F79 darwin-arm64, locale en-SG)
-  Xcode - develop for iOS and macOS (Xcode 14.2)
- `wogaa_flutter_tracker` version: v2.0.0

**Additional Context:**
It would be great if the package could be updated to support null safety. More information on enabling null safety can be found here: https://dart.dev/null-safety

---
